### ISSUE TITLE
 I met this error when run anoGAN:

### ISSUE THREAD

**Issue by bemoregt** [AndersonJo/gan-yhat#1]
Hi, @AndersonJo 

I met this error when run anoGAN:

<ipython-input-9-a93d71f45161> in load_image_data(dir_path)
      4 def load_image_data(dir_path):
      5     if not os.path.exists(dir_path):
----> 6         raise Exception('The anomalous data does not exists.'
      7                         'The data is owned by EXEM company.')
      8 

Exception: The anomalous data does not exists.The data is owned by EXEM company.
-----------------------------------------------------------------------

How can I get those data?

Thanks in advance.

from @bemoregt.

**Comment by AndersonJo** [comment]
I answered this question in the following issue. 
[At train AnoGAN with MNIST data, Does the train set and test set all contain only normal data?](https://github.com/AndersonJo/gan-yhat/issues/2)

Unfortunately, the abnormal data is proprietary data. 
But it is easy to make your own abnormal data. 

1. Open photoshop
2. Modify normal image (fastion MNIST) such that the image looks abnormal.
3. Use the abnormal data you made as validation dataset (I mean, the Anogan
is trained done at this time)

I will close this issue.
